/**
 * ClearBite Central Live Food & Restaurant Dataset
 * Comprehensive with live ingredient origins, allergen matrix, micronutrients & customizable options for each restaurant.
 */

export const restaurants = [
  {
    id: 'the-green-bowl',
    numericId: 1,
    name: 'The Green Bowl',
    tagline: 'Organic, Plant-Forward & Macro-Balanced Bowls',
    image: '/hd-restaurant-the-green-bowl.jpg',
    galleryImages: [
      { id: 1, src: '/quinoa-power-bowl.jpg', alt: 'Quinoa Power Bowl' },
      { id: 2, src: '/grilled-chicken-salad.jpg', alt: 'Grilled Chicken Salad' },
      { id: 3, src: '/mediterranean-bowl.jpg', alt: 'Mediterranean Mezze Bowl' },
      { id: 4, src: '/avocado-wrap.jpg', alt: 'Avocado Green Goddess Wrap' },
      { id: 5, src: '/dark-bowl-salad.jpg', alt: 'Fresh Kitchen Preparation', isVideo: true },
    ],
    rating: 4.5,
    reviews: '2k+',
    deliveryTime: '30–40 mins',
    priceForTwo: '₹300 for two',
    cuisines: ['Healthy', 'Vegan', 'Continental'],
    category: 'healthy',
    offer: 'Flat 30% OFF',
    description:
      'Nutrient-dense superfood bowls, crisp organic salads, and artisan whole-grain wraps made with zero artificial preservatives and 100% transparent ingredient sourcing.',
    about: {
      philosophy: 'Clean eating made effortless with whole ancient grains, pesticide-free hydroponic greens, and cold-pressed extra virgin oils.',
      hygieneScore: '99/100',
      kitchenCert: 'FSSAI 5-Star Clean Certified Kitchen',
      sourcing: 'Daily harvests from Nilgiri organic cooperatives and local hydroponic greenhouses.',
      certifications: ['100% Non-GMO', 'No Added MSG', 'Zero Trans Fats', 'ISO 22000'],
    },
    menuCategories: ['all', 'bowls', 'salads', 'wraps', 'drinks'],
    menuItemIds: [
      'quinoa-power-bowl',
      'grilled-chicken-salad',
      'mediterranean-bowl',
      'avocado-wrap',
      'mango-smoothie',
    ],
  },
  {
    id: 'spice-route',
    numericId: 2,
    name: 'Spice Route',
    tagline: 'Authentic Indian Curries, Royal Dum Biryanis & Clay Oven Delicacies',
    image: '/hd-restaurant-spice-route.jpg',
    galleryImages: [
      { id: 1, src: '/cuisine-indian.jpg', alt: 'Royal Awadhi Dum Biryani' },
      { id: 2, src: '/card1_test.jpg', alt: 'Slow-Simmered Dal Makhani' },
      { id: 3, src: '/card2_test.jpg', alt: 'Paneer Tikka Masala' },
      { id: 4, src: '/hd-restaurant-spice-route.jpg', alt: 'Heritage Spices & Tandoor' },
    ],
    rating: 4.3,
    reviews: '1k+',
    deliveryTime: '25–35 mins',
    priceForTwo: '₹450 for two',
    cuisines: ['Indian', 'North Indian', 'Biryani'],
    category: 'indian',
    offer: 'Up to 40% OFF',
    description:
      'Heritage North Indian dining featuring slow-dum biryanis, stone-ground garam masalas, pure A2 cow ghee, and tender charcoal-grilled meats and paneer.',
    about: {
      philosophy: 'Honoring ancient royal Mughlai recipes using stone-ground whole spices, cold-pressed mustard oil, and naturally aged basmati rice.',
      hygieneScore: '98/100',
      kitchenCert: 'FSSAI Certified Heritage Cloud Kitchen',
      sourcing: 'Whole spices sourced from Idukki spice plantations, aged basmati from Dehradun.',
      certifications: ['Pure Cow Ghee', 'Zero Artificial Food Colors', 'No Palm Oil'],
    },
    menuCategories: ['all', 'biryani', 'curries', 'tandoor', 'breads'],
    menuItemIds: [
      'royal-awadhi-biryani',
      'dal-makhani-special',
      'paneer-tikka-masala',
      'tandoori-herb-chicken',
      'fresh-garlic-naan',
    ],
  },
  {
    id: 'la-pizzeria',
    numericId: 3,
    name: 'La Pizzeria',
    tagline: 'Authentic Italian Sourdough Pizzas & Handcrafted Pasta',
    image: '/hd-restaurant-la-pizzeria.jpg',
    galleryImages: [
      { id: 1, src: '/cuisine-continental.jpg', alt: 'Artisan Margherita Rustica' },
      { id: 2, src: '/pesto-pasta.jpg', alt: 'Zesty Basil Pesto Penne' },
      { id: 3, src: '/card3_test.jpg', alt: 'Truffle Mushroom Sourdough Pizza' },
      { id: 4, src: '/hd-restaurant-la-pizzeria.jpg', alt: 'Italian Woodfired Oven' },
    ],
    rating: 4.6,
    reviews: '3k+',
    deliveryTime: '30–45 mins',
    priceForTwo: '₹500 for two',
    cuisines: ['Pizza', 'Italian', 'Pastas'],
    category: 'pizza',
    offer: 'Flat 25% OFF',
    description:
      '48-hour naturally fermented Italian sourdough pizzas baked at 450°C with San Marzano tomatoes, artisanal burrata, and fresh Genovese basil.',
    about: {
      philosophy: 'Traditional Italian slow-fermentation crafted with Caputo 00 flour and virgin olive oil for effortless digestion and maximum flavor.',
      hygieneScore: '99/100',
      kitchenCert: 'Artisanal Italian Bakery Standard',
      sourcing: 'San Marzano DOP Tomatoes from Campania, Extra Virgin Olive Oil from Tuscany.',
      certifications: ['48-Hr Fermented Crust', 'DOP Certified Cheese', 'Zero Dough Conditioners'],
    },
    menuCategories: ['all', 'pizza', 'pastas', 'starters'],
    menuItemIds: [
      'margherita-rustica',
      'truffle-mushroom-pizza',
      'basil-pesto-penne',
      'woodfired-burrata-salad',
    ],
  },
  {
    id: 'burger-hub',
    numericId: 4,
    name: 'Burger Hub',
    tagline: 'Artisan Gourmet Smashed Burgers & Hand-Cut Seasoned Fries',
    image: '/hd-restaurant-burger-hub.jpg',
    galleryImages: [
      { id: 1, src: '/cuisine-fastfood.jpg', alt: 'Truffle Smash Gourmet Burger' },
      { id: 2, src: '/checkout-fries.jpg', alt: 'Rosemary Sea Salt Fries' },
      { id: 3, src: '/card4_test.jpg', alt: 'Flame Grilled Chicken Burger' },
      { id: 4, src: '/hd-restaurant-burger-hub.jpg', alt: 'Craft Burger Kitchen' },
    ],
    rating: 4.4,
    reviews: '2k+',
    deliveryTime: '20–30 mins',
    priceForTwo: '₹350 for two',
    cuisines: ['Burgers', 'Fast Food', 'American'],
    category: 'burgers',
    offer: 'Up to 35% OFF',
    description:
      'Brioche buns baked daily, grass-fed and plant-based smashed patties, homemade pickles, and triple-cooked non-GMO fries.',
    about: {
      philosophy: 'Elevating comfort burgers with gourmet chef techniques, real whole cheeses, and zero processed fillers.',
      hygieneScore: '98/100',
      kitchenCert: 'Certified Fresh Grill House',
      sourcing: 'Brioche buns from local artisanal bakeries, non-GMO hand-cut potatoes.',
      certifications: ['Zero Trans Fats', 'Antibiotic-Free Poultry', 'Fresh Daily Ground'],
    },
    menuCategories: ['all', 'burgers', 'sides', 'shakes'],
    menuItemIds: [
      'truffle-smash-burger',
      'flame-grilled-chicken-burger',
      'crispy-paneer-deluxe-burger',
      'rosemary-sea-salt-fries',
    ],
  },
  {
    id: 'urban-asia',
    numericId: 5,
    name: 'Urban Asia',
    tagline: 'Pan-Asian Wok Noodles, Steamed Dimsums & Rich Thai Curries',
    image: '/hd-restaurant-urban-asia.jpg',
    galleryImages: [
      { id: 1, src: '/cuisine-chinese.jpg', alt: 'Pad Thai Wok Tossed Noodles' },
      { id: 2, src: '/info-noodle-bowl.jpg', alt: 'Steamed Edamame Dimsums' },
      { id: 3, src: '/card5_test.jpg', alt: 'Thai Green Herb Curry' },
      { id: 4, src: '/hd-restaurant-urban-asia.jpg', alt: 'Live Asian Wok Station' },
    ],
    rating: 4.5,
    reviews: '1k+',
    deliveryTime: '25–40 mins',
    priceForTwo: '₹450 for two',
    cuisines: ['Chinese', 'Thai', 'Asian'],
    category: 'chinese',
    offer: 'Flat 30% OFF',
    description:
      'Vibrant wok-tossed Asian delicacies, handcrafted crystal dimsums, fresh lemongrass broths, and authentic stone-ground Thai curry pastes.',
    about: {
      philosophy: 'Fast-heat wok cooking that preserves vegetable crunch, micronutrients, and vibrant aromatic aromatics.',
      hygieneScore: '99/100',
      kitchenCert: 'Pan-Asian Master Certified Kitchen',
      sourcing: 'Kaffir lime leaves & Thai galangal directly imported, fresh local Asian greens.',
      certifications: ['Zero Added MSG', 'Low-Sodium Tamari Options', '100% Sesame Oil'],
    },
    menuCategories: ['all', 'dimsums', 'noodles', 'curries'],
    menuItemIds: [
      'edamame-truffle-dimsums',
      'pad-thai-wok-noodles',
      'thai-green-curry-bowl',
      'teriyaki-tofu-rice-bowl',
    ],
  },
  {
    id: 'tandoor-tales',
    numericId: 6,
    name: 'Tandoor Tales',
    tagline: 'Royal Tandoori Roasts, Mughlai Curries & Authentic Dum Biryanis',
    image: '/hd-restaurant-tandoor-tales.jpg',
    galleryImages: [
      { id: 1, src: '/hd-restaurant-tandoor-tales.jpg', alt: 'Clay Oven Tandoor' },
      { id: 2, src: '/cuisine-indian.jpg', alt: 'Bhatti Ka Murgh' },
      { id: 3, src: '/card6_test.jpg', alt: 'Zaffrani Malai Paneer' },
      { id: 4, src: '/card7_test.jpg', alt: 'Hyderabadi Dum Biryani' },
    ],
    rating: 4.4,
    reviews: '800+',
    deliveryTime: '30–45 mins',
    priceForTwo: '₹500 for two',
    cuisines: ['Indian', 'Tandoor', 'Mughlai'],
    category: 'indian',
    offer: 'Up to 40% OFF',
    description:
      'Traditional charcoal clay oven cooking with rich marinade infusions of saffron, hung curd, smoked spices, and slow-braised curries.',
    about: {
      philosophy: 'Authentic clay pot smoke infusions, zero artificial food coloring, and slow-roast techniques passed down through generations.',
      hygieneScore: '98/100',
      kitchenCert: 'Clay Pot Safety Verified Kitchen',
      sourcing: 'Locally churned farm curd, saffron from Pampore Kashmir.',
      certifications: ['Pure Desi Ghee', 'Free Range Poultry', 'Zero Preservatives'],
    },
    menuCategories: ['all', 'tandoor', 'biryani', 'curries'],
    menuItemIds: [
      'bhatti-ka-murgh',
      'zaffrani-malai-paneer-tikka',
      'hyderabadi-dum-biryani',
      'smoked-dal-tadka',
    ],
  },
  {
    id: 'healthy-bites',
    numericId: 7,
    name: 'Healthy Bites',
    tagline: 'Clean Macro Nutrition, Cold-Pressed Juices & Superfood Greens',
    image: '/hd-restaurant-healthy-bites.jpg',
    galleryImages: [
      { id: 1, src: '/cuisine-healthy.jpg', alt: 'Citrus Herb Protein Salad' },
      { id: 2, src: '/mango-smoothie.jpg', alt: 'Mango Chia Super Smoothie' },
      { id: 3, src: '/avocado-wrap.jpg', alt: 'Energy Protein Wrap' },
      { id: 4, src: '/hd-restaurant-healthy-bites.jpg', alt: 'Clean Kitchen Bar' },
    ],
    rating: 4.6,
    reviews: '1k+',
    deliveryTime: '20–30 mins',
    priceForTwo: '₹350 for two',
    cuisines: ['Healthy', 'Salads', 'Smoothies'],
    category: 'healthy',
    offer: 'Flat 25% OFF',
    description:
      'Calorie-counted, chef-curated balanced meals for weight management, gym enthusiasts, and conscious healthy lifestyles.',
    about: {
      philosophy: 'Every meal is formulated alongside certified nutritionists with calculated macronutrients and transparent ingredient origins.',
      hygieneScore: '100/100',
      kitchenCert: 'Nutritional Hygiene Certified',
      sourcing: 'Daily cold-pressed raw oils, organic baby greens, microgreens from local urban farms.',
      certifications: ['Exact Calorie Counted', 'Sugar-Free Smoothies', 'Keto & Vegan Certified'],
    },
    menuCategories: ['all', 'salads', 'wraps', 'smoothies'],
    menuItemIds: [
      'citrus-herb-chicken-salad',
      'green-detox-bowl',
      'avocado-wrap',
      'mango-smoothie',
    ],
  },
  {
    id: 'sweet-cravings',
    numericId: 8,
    name: 'Sweet Cravings',
    tagline: 'Gourmet Artisanal Patisserie, Cheesecakes & Refined Sugar-Free Desserts',
    image: '/hd-restaurant-sweet-cravings.jpg',
    galleryImages: [
      { id: 1, src: '/cuisine-desserts.jpg', alt: 'Belgian Dark Ganache Cake' },
      { id: 2, src: '/checkout-brownie.jpg', alt: 'Walnut Fudge Brownie' },
      { id: 3, src: '/card8_test.jpg', alt: 'New York Baked Berry Cheesecake' },
      { id: 4, src: '/hd-restaurant-sweet-cravings.jpg', alt: 'Artisan Bakery Display' },
    ],
    rating: 4.7,
    reviews: '1k+',
    deliveryTime: '15–25 mins',
    priceForTwo: '₹280 for two',
    cuisines: ['Desserts', 'Bakery', 'Patisserie'],
    category: 'desserts',
    offer: 'Up to 30% OFF',
    description:
      'French and European confectionery crafted with 70% Belgian chocolate, Madagascar vanilla beans, almond flour, and zero refined white sugar.',
    about: {
      philosophy: 'Indulgent yet clean pastry arts using raw jaggery, unrefined coconut sugar, and premium cold-churned cream.',
      hygieneScore: '99/100',
      kitchenCert: 'Master French Pastry Standard',
      sourcing: 'Fair-Trade Belgian Cocoa, French Cultured Butter, Real Berry Compotes.',
      certifications: ['Zero Artificial Sweeteners', 'Gluten-Free Flour Bases', 'Eggless Options'],
    },
    menuCategories: ['all', 'cakes', 'cheesecakes', 'brownies'],
    menuItemIds: [
      'belgian-dark-ganache-cake',
      'ny-baked-berry-cheesecake',
      'walnut-fudge-brownie',
      'mango-smoothie',
    ],
  },
];

/* =========================================================
   Comprehensive Food & Nutrition Dataset (All Dishes)
   ========================================================= */

export const foodItems = [
  /* ---------------- THE GREEN BOWL ---------------- */
  {
    id: 'quinoa-power-bowl',
    restaurantId: 'the-green-bowl',
    name: 'Quinoa Power Bowl',
    price: 249,
    rating: 4.8,
    reviewsCount: 340,
    image: '/quinoa-power-bowl.jpg',
    category: 'bowls',
    tagline: '100% Organic Tri-Color Quinoa with Fire-Roasted Seasonal Veggies & Lemon Tahini',
    description:
      'A wholesome bowl crafted with organic Andean tri-color quinoa, Hass avocado, steamed hydroponic broccoli, roasted Nilgiri carrots, cherry tomatoes, superfood seeds, and zesty house lemon tahini vinaigrette.',
    prepTime: '15-20 mins',
    dietaryFlags: { isVegan: true, isVegetarian: true, isGlutenFree: true, isDairyFree: true, isKeto: false, isNutFree: false, isOrganic: true },
    dietaryBadges: [
      { id: 'vegan', label: '100% Vegan', icon: '🌱', color: '#16a34a', bg: '#dcfce7' },
      { id: 'glutenFree', label: 'Gluten-Free', icon: '🌾', color: '#0d9488', bg: '#ccfbf1' },
      { id: 'highFiber', label: 'High Fiber (9.5g)', icon: '🥗', color: '#059669', bg: '#e8f5ec' },
    ],
    allergens: {
      contains: [{ name: 'Sesame', severity: 'moderate', icon: '🌱', note: 'In Lemon Tahini' }],
      freeFrom: ['Gluten', 'Dairy', 'Eggs', 'Peanuts', 'Soy', 'Shellfish'],
      crossContactNote: 'Prepared in an ISO-certified clean kitchen with isolated allergen prep stations.',
    },
    nutrition: {
      servingSize: '380g', calories: 450, protein: 18, carbs: 52, fats: 14, fiber: 9.5, sodium: 320, sugar: 4.2,
      micronutrients: [
        { name: 'Potassium', value: '720 mg', dv: '15%' },
        { name: 'Iron', value: '4.8 mg', dv: '27%' },
        { name: 'Magnesium', value: '118 mg', dv: '28%' },
      ],
    },
    ingredients: [
      { id: 'quinoa', name: 'Tri-Color Quinoa', icon: '🥣', category: 'Ancient Grain Base', origin: 'Certified Organic High-Altitude Farms', benefit: 'Complete plant protein loaded with all 9 essential amino acids.', calories: 140, protein: 5.2, allergens: [], certifications: ['USDA Organic', 'Non-GMO'] },
      { id: 'avocado', name: 'Hass Avocado', icon: '🥑', category: 'Healthy Fats', origin: 'Tree-ripened, hand-sliced daily', benefit: 'Rich in monounsaturated oleic acid and potassium.', calories: 90, protein: 1.2, allergens: [], certifications: ['Fresh Farm Picked'] },
      { id: 'broccoli', name: 'Steamed Broccoli', icon: '🥦', category: 'Cruciferous Greens', origin: 'Local Hydroponic Greenhouse', benefit: 'Packed with sulforaphane and Vitamin C.', calories: 30, protein: 2.8, allergens: [], certifications: ['Pesticide Free'] },
      { id: 'seeds', name: 'Chia & Pumpkin Seeds', icon: '🌰', category: 'Superfood Crunch', origin: 'Raw Unprocessed Sun-Dried', benefit: 'High-density plant Omega-3 fatty acids & zinc.', calories: 55, protein: 3.4, allergens: ['Seeds'], certifications: ['Raw Superfood'] },
    ],
    customizationOptions: {
      bases: {
        title: 'Choose Base Grain / Greens', required: true, maxSelect: 1,
        options: [
          { id: 'tri-quinoa', name: 'Tri-Color Organic Quinoa (Standard)', price: 0, calories: 140, protein: 5.2, allergens: [] },
          { id: 'cauli-rice', name: 'Low-Carb Cauliflower Rice', price: 25, calories: 45, protein: 2.1, allergens: [] },
        ],
      },
      proteins: {
        title: 'Add Extra Protein', required: false, maxSelect: 2,
        options: [
          { id: 'grilled-tofu', name: 'Smoked Garlic Herb Tofu', price: 40, calories: 95, protein: 12, allergens: ['Soy'] },
          { id: 'grilled-chicken', name: 'Flame Grilled Herb Chicken', price: 65, calories: 130, protein: 26, allergens: [] },
        ],
      },
      toppings: {
        title: 'Superfood Add-Ons', required: false, maxSelect: 3,
        options: [
          { id: 'extra-avocado', name: 'Extra Half Hass Avocado', price: 45, calories: 85, protein: 1.2, allergens: [] },
          { id: 'mushrooms', name: 'Roasted Shiitake Mushrooms', price: 30, calories: 35, protein: 2.2, allergens: [] },
        ],
      },
      dressings: {
        title: 'Artisan Dressing', required: true, maxSelect: 1,
        options: [
          { id: 'lemon-tahini', name: 'Creamy Lemon Tahini', price: 0, calories: 65, protein: 1.8, allergens: ['Sesame'] },
          { id: 'balsamic', name: 'Aged Balsamic Dijon Glaze', price: 0, calories: 45, protein: 0.5, allergens: [] },
        ],
      },
    },
  },
  {
    id: 'grilled-chicken-salad',
    restaurantId: 'the-green-bowl',
    name: 'Grilled Chicken Protein Salad',
    price: 269,
    rating: 4.9,
    reviewsCount: 280,
    image: '/grilled-chicken-salad.jpg',
    category: 'salads',
    tagline: 'Antibiotic-Free Herb Chicken, Mixed Hydroponic Greens & Cold-Pressed Olive Oil',
    description: 'Skinless antibiotic-free chicken breast seared with rosemary and thyme, served over crisp mixed greens, cucumber ribbons, bell peppers and drizzled with cold-pressed extra virgin olive oil.',
    prepTime: '15-20 mins',
    dietaryFlags: { isVegan: false, isVegetarian: false, isGlutenFree: true, isDairyFree: true, isKeto: true, isNutFree: true, isOrganic: true },
    dietaryBadges: [
      { id: 'highProtein', label: 'High Protein (34g)', icon: '🍗', color: '#b45309', bg: '#fef3c7' },
      { id: 'keto', label: 'Keto Friendly', icon: '🥑', color: '#0d9488', bg: '#ccfbf1' },
      { id: 'glutenFree', label: 'Gluten-Free', icon: '🌾', color: '#059669', bg: '#dcfce7' },
    ],
    allergens: { contains: [], freeFrom: ['Gluten', 'Dairy', 'Nuts', 'Sesame', 'Soy', 'Shellfish'], crossContactNote: 'Cooked on a dedicated poultry grill with clean utensils.' },
    nutrition: { servingSize: '350g', calories: 390, protein: 34, carbs: 16, fats: 18, fiber: 6.2, sodium: 410, sugar: 3.1, micronutrients: [{ name: 'Niacin (B3)', value: '14 mg', dv: '88%' }, { name: 'Selenium', value: '32 mcg', dv: '58%' }] },
    ingredients: [
      { id: 'chicken', name: 'Herb Grilled Chicken', icon: '🍗', category: 'Lean Protein', origin: 'Antibiotic-Free Farm Poultry', benefit: 'Lean complete amino acid profile for muscle recovery.', calories: 180, protein: 28, allergens: [], certifications: ['Antibiotic-Free'] },
      { id: 'greens', name: 'Baby Spinach & Romaine', icon: '🥬', category: 'Greens', origin: 'Vertical Hydroponic Greens', benefit: 'High hydration and rich in potassium and Vitamin K.', calories: 25, protein: 2, allergens: [], certifications: ['Pesticide Free'] },
    ],
    customizationOptions: {
      bases: { title: 'Salad Base', required: true, maxSelect: 1, options: [{ id: 'greens', name: 'Crisp Romaine & Spinach', price: 0, calories: 25, protein: 2, allergens: [] }] },
      proteins: { title: 'Protein', required: false, maxSelect: 1, options: [{ id: 'double-chicken', name: 'Double Chicken Breast (+100g)', price: 70, calories: 150, protein: 28, allergens: [] }] },
      toppings: { title: 'Add-Ons', required: false, maxSelect: 2, options: [{ id: 'parmesan', name: 'Shaved Aged Parmesan', price: 35, calories: 60, protein: 4.5, allergens: ['Dairy'] }] },
      dressings: { title: 'Dressing', required: true, maxSelect: 1, options: [{ id: 'olive-lemon', name: 'EVOO & Lemon', price: 0, calories: 70, protein: 0, allergens: [] }] },
    },
  },
  {
    id: 'mediterranean-bowl',
    restaurantId: 'the-green-bowl',
    name: 'Mediterranean Mezze Bowl',
    price: 279,
    rating: 4.7,
    reviewsCount: 215,
    image: '/mediterranean-bowl.jpg',
    category: 'bowls',
    tagline: 'Baked Herb Falafels, Stone-Ground Hummus, Tabbouleh & Greek Olives',
    description: 'Golden herb-baked chickpea falafels with stone-ground sesame hummus, heirloom tabbouleh, pickled red cabbage, cucumber salad, and warm pita wedges.',
    prepTime: '15-20 mins',
    dietaryFlags: { isVegan: true, isVegetarian: true, isGlutenFree: false, isDairyFree: true, isKeto: false, isNutFree: true, isOrganic: true },
    dietaryBadges: [
      { id: 'vegan', label: '100% Vegan', icon: '🌱', color: '#16a34a', bg: '#dcfce7' },
      { id: 'highFiber', label: 'High Fiber (11g)', icon: '🥗', color: '#059669', bg: '#e8f5ec' },
    ],
    allergens: { contains: [{ name: 'Sesame', severity: 'moderate', icon: '🌱', note: 'In Hummus' }], freeFrom: ['Dairy', 'Eggs', 'Nuts', 'Shellfish'], crossContactNote: 'Gluten-free base substitute available.' },
    nutrition: { servingSize: '410g', calories: 510, protein: 19, carbs: 68, fats: 17, fiber: 11.4, sodium: 480, sugar: 5.5, micronutrients: [{ name: 'Iron', value: '5.2 mg', dv: '29%' }] },
    ingredients: [
      { id: 'falafel', name: 'Baked Herb Falafel', icon: '🧆', category: 'Plant Protein', origin: 'Handcrafted fresh daily', benefit: 'Spiced chickpeas baked with parsley and coriander.', calories: 160, protein: 7, allergens: [], certifications: ['Non-Fried'] },
      { id: 'hummus', name: 'Stone-Ground Hummus', icon: '🫒', category: 'Dip', origin: 'Traditional Greek Olive Oil Recipe', benefit: 'Rich in dietary fiber and healthy fats.', calories: 110, protein: 4.5, allergens: ['Sesame'], certifications: ['Artisan Crafted'] },
    ],
    customizationOptions: {
      bases: { title: 'Base', required: true, maxSelect: 1, options: [{ id: 'tabbouleh', name: 'Parsley Bulgur Tabbouleh', price: 0, calories: 120, protein: 3, allergens: ['Gluten'] }] },
      proteins: { title: 'Extra Mezze', required: false, maxSelect: 1, options: [{ id: 'falafel-extra', name: '3 Extra Baked Falafels', price: 45, calories: 120, protein: 6, allergens: [] }] },
      toppings: { title: 'Pickles', required: false, maxSelect: 2, options: [{ id: 'olives', name: 'Kalamata Olives', price: 25, calories: 40, protein: 0.5, allergens: [] }] },
      dressings: { title: 'Sauce', required: true, maxSelect: 1, options: [{ id: 'tahini', name: 'Garlic Tahini Sauce', price: 0, calories: 60, protein: 1.5, allergens: ['Sesame'] }] },
    },
  },
  {
    id: 'avocado-wrap',
    restaurantId: 'the-green-bowl',
    name: 'Avocado Green Goddess Wrap',
    price: 199,
    rating: 4.7,
    reviewsCount: 190,
    image: '/avocado-wrap.jpg',
    category: 'wraps',
    tagline: 'Whole Wheat Spinach Tortilla, Smashed Hass Avocado & Sprouted Mung',
    description: 'Whole wheat spinach wrap packed with smashed avocado, crunchy sprouted legumes, cucumber matchsticks, and herb green goddess sauce.',
    prepTime: '10-15 mins',
    dietaryFlags: { isVegan: true, isVegetarian: true, isGlutenFree: false, isDairyFree: true, isKeto: false, isNutFree: true, isOrganic: true },
    dietaryBadges: [
      { id: 'vegan', label: '100% Vegan', icon: '🌱', color: '#16a34a', bg: '#dcfce7' },
      { id: 'fiber', label: 'High Fiber', icon: '🥑', color: '#059669', bg: '#e8f5ec' },
    ],
    allergens: { contains: [{ name: 'Gluten', severity: 'mild', icon: '🌾', note: 'In Wrap Tortilla' }], freeFrom: ['Dairy', 'Eggs', 'Nuts', 'Peanuts'], crossContactNote: 'Clean board prep.' },
    nutrition: { servingSize: '290g', calories: 360, protein: 12, carbs: 46, fats: 14, fiber: 8.5, sodium: 340, sugar: 3.2, micronutrients: [{ name: 'Vitamin E', value: '3.4 mg', dv: '23%' }] },
    ingredients: [
      { id: 'avocado', name: 'Hass Avocado', icon: '🥑', category: 'Healthy Fats', origin: 'Fresh Tree-Ripened', benefit: 'Heart-healthy monounsaturated fats.', calories: 120, protein: 1.5, allergens: [], certifications: ['Fresh Picked'] },
    ],
    customizationOptions: {
      bases: { title: 'Wrap Type', required: true, maxSelect: 1, options: [{ id: 'spinach-wrap', name: 'Spinach Whole Wheat Wrap', price: 0, calories: 130, protein: 4, allergens: ['Gluten'] }] },
      proteins: { title: 'Extra Protein', required: false, maxSelect: 1, options: [{ id: 'tofu-cube', name: 'Spiced Tofu Cubes', price: 35, calories: 70, protein: 8, allergens: ['Soy'] }] },
      toppings: { title: 'Crunch', required: false, maxSelect: 2, options: [{ id: 'sprouts', name: 'Sprouted Mung Beans', price: 15, calories: 25, protein: 2.5, allergens: [] }] },
      dressings: { title: 'Sauce', required: true, maxSelect: 1, options: [{ id: 'green-goddess', name: 'Avocado Green Goddess', price: 0, calories: 50, protein: 1, allergens: [] }] },
    },
  },
  {
    id: 'mango-smoothie',
    restaurantId: 'the-green-bowl',
    name: 'Mango Chia Protein Smoothie',
    price: 179,
    rating: 4.8,
    reviewsCount: 160,
    image: '/mango-smoothie.jpg',
    category: 'drinks',
    tagline: 'Alphonso Mango, Plant Pea Protein, Chia Seeds & Almond Milk',
    description: 'Silky smooth high-protein blend of naturally sweet Alphonso mangoes, organic chia seeds, plant pea protein isolate, and unsweetened almond milk.',
    prepTime: '5-10 mins',
    dietaryFlags: { isVegan: true, isVegetarian: true, isGlutenFree: true, isDairyFree: true, isKeto: false, isNutFree: false, isOrganic: true },
    dietaryBadges: [
      { id: 'vegan', label: '100% Vegan', icon: '🌱', color: '#16a34a', bg: '#dcfce7' },
      { id: 'protein', label: '15g Plant Protein', icon: '💪', color: '#b45309', bg: '#fef3c7' },
    ],
    allergens: { contains: [{ name: 'Almond', severity: 'mild', icon: '🌰', note: 'In Almond Milk' }], freeFrom: ['Dairy', 'Gluten', 'Eggs', 'Soy'], crossContactNote: 'Nut-free oat milk substitution available.' },
    nutrition: { servingSize: '350ml', calories: 240, protein: 15, carbs: 32, fats: 5, fiber: 6, sodium: 90, sugar: 18, micronutrients: [{ name: 'Vitamin A', value: '850 IU', dv: '35%' }] },
    ingredients: [
      { id: 'mango', name: 'Alphonso Mango', icon: '🥭', category: 'Fruit Base', origin: 'Ratnagiri Orchard Harvest', benefit: 'Rich in beta-carotene, Vitamin C, and natural enzymes.', calories: 95, protein: 1, allergens: [], certifications: ['Naturally Ripened'] },
    ],
    customizationOptions: {
      bases: { title: 'Milk Base', required: true, maxSelect: 1, options: [{ id: 'almond-milk', name: 'Unsweetened Almond Milk', price: 0, calories: 40, protein: 1.5, allergens: ['Tree Nuts'] }, { id: 'oat-milk', name: 'Creamy Gluten-Free Oat Milk', price: 15, calories: 60, protein: 2, allergens: [] }] },
      proteins: { title: 'Protein Boost', required: false, maxSelect: 1, options: [{ id: 'extra-scoop', name: 'Extra Scoop Plant Protein (+10g)', price: 35, calories: 45, protein: 10, allergens: [] }] },
      toppings: { title: 'Superfood Add-Ons', required: false, maxSelect: 1, options: [{ id: 'flaxseed', name: 'Ground Golden Flaxseeds', price: 15, calories: 30, protein: 1.2, allergens: [] }] },
      dressings: { title: 'Sweetness', required: true, maxSelect: 1, options: [{ id: 'no-sugar', name: 'No Added Sweetener (Natural Fruit Only)', price: 0, calories: 0, protein: 0, allergens: [] }] },
    },
  },

  /* ---------------- SPICE ROUTE ---------------- */
  {
    id: 'royal-awadhi-biryani',
    restaurantId: 'spice-route',
    name: 'Royal Awadhi Dum Biryani',
    price: 349,
    rating: 4.8,
    reviewsCount: 420,
    image: '/cuisine-indian.jpg',
    category: 'biryani',
    tagline: 'Aged Dehradun Basmati, Saffron, Spiced Marinated Chicken & Pure Desi Ghee',
    description: 'Slow-cooked in a sealed clay handi with layers of fragrant 2-year aged basmati rice, tender farm-raised chicken, Kashmiri saffron, caramelised onions, and fresh mint.',
    prepTime: '25-30 mins',
    dietaryFlags: { isVegan: false, isVegetarian: false, isGlutenFree: true, isDairyFree: false, isKeto: false, isNutFree: false, isOrganic: false },
    dietaryBadges: [
      { id: 'highProtein', label: 'High Protein (28g)', icon: '🍗', color: '#b45309', bg: '#fef3c7' },
      { id: 'pureGhee', label: 'Pure Cow Ghee', icon: '🧈', color: '#ca8a04', bg: '#fef9c3' },
      { id: 'glutenFree', label: 'Gluten-Free', icon: '🌾', color: '#059669', bg: '#dcfce7' },
    ],
    allergens: { contains: [{ name: 'Dairy', severity: 'moderate', icon: '🥛', note: 'In Desi Ghee & Marinade Curd' }], freeFrom: ['Gluten', 'Eggs', 'Soy', 'Shellfish'], crossContactNote: 'Cooked in sealed handis.' },
    nutrition: { servingSize: '450g', calories: 620, protein: 28, carbs: 74, fats: 22, fiber: 4.5, sodium: 580, sugar: 3.5, micronutrients: [{ name: 'Iron', value: '4.2 mg', dv: '23%' }, { name: 'Zinc', value: '3.8 mg', dv: '35%' }] },
    ingredients: [
      { id: 'basmati', name: 'Aged Basmati Rice', icon: '🍚', category: 'Grain', origin: 'Dehradun Valley Heritage Farms', benefit: 'Aged 24 months for long fluffy non-sticky aromatic grains.', calories: 210, protein: 4.2, allergens: [], certifications: ['Aged 2 Years'] },
      { id: 'chicken', name: 'Tender Spiced Chicken', icon: '🍗', category: 'Protein', origin: 'Farm-Raised Antibiotic-Free', benefit: 'Slow marinated in ginger-garlic, hung curd and cardamom.', calories: 190, protein: 24, allergens: ['Dairy'], certifications: ['Antibiotic-Free'] },
      { id: 'saffron', name: 'Pampore Saffron & Ghee', icon: '✨', category: 'Aromatics', origin: 'Kashmir Saffron Cooperative', benefit: 'Potent natural antioxidants and natural mood elevation.', calories: 80, protein: 0.2, allergens: ['Dairy'], certifications: ['Pure Grade 1'] },
    ],
    customizationOptions: {
      bases: { title: 'Spice Level', required: true, maxSelect: 1, options: [{ id: 'medium', name: 'Medium Fragrant Awadhi Spice', price: 0, calories: 0, protein: 0, allergens: [] }, { id: 'spicy', name: 'Extra Spicy Mirchi Salan Style', price: 0, calories: 15, protein: 0, allergens: [] }] },
      proteins: { title: 'Portion Size', required: false, maxSelect: 1, options: [{ id: 'extra-chicken', name: 'Double Chicken Pieces (+2 pcs)', price: 80, calories: 120, protein: 18, allergens: [] }] },
      toppings: { title: 'Accompaniments', required: false, maxSelect: 2, options: [{ id: 'burani-raita', name: 'Garlic Burani Raita', price: 35, calories: 60, protein: 3, allergens: ['Dairy'] }, { id: 'salan', name: 'Classic Peanut Sesame Salan Gravy', price: 40, calories: 90, protein: 2, allergens: ['Peanuts', 'Sesame'] }] },
      dressings: { title: 'Ghee Finishing', required: true, maxSelect: 1, options: [{ id: 'standard-ghee', name: 'Standard Saffron Ghee Glaze', price: 0, calories: 45, protein: 0, allergens: ['Dairy'] }, { id: 'low-oil', name: 'Light Ghee (Diet Friendly)', price: 0, calories: 0, protein: 0, allergens: [] }] },
    },
  },
  {
    id: 'dal-makhani-special',
    restaurantId: 'spice-route',
    name: 'Slow-Simmered Dal Makhani',
    price: 249,
    rating: 4.7,
    reviewsCount: 310,
    image: '/card1_test.jpg',
    category: 'curries',
    tagline: '24-Hour Woodfire Simmered Black Lentils, Fresh Tomatoes & Churned Butter',
    description: 'Whole organic black urad lentils and kidney beans slow-cooked overnight with vine-ripened tomatoes, white churned butter, and subtle smoked fenugreek leaves.',
    prepTime: '20-25 mins',
    dietaryFlags: { isVegan: false, isVegetarian: true, isGlutenFree: true, isDairyFree: false, isKeto: false, isNutFree: true, isOrganic: true },
    dietaryBadges: [
      { id: 'veg', label: 'Pure Veg', icon: '🥬', color: '#16a34a', bg: '#dcfce7' },
      { id: 'protein', label: 'Plant Protein (16g)', icon: '🥣', color: '#059669', bg: '#e8f5ec' },
      { id: 'slowCooked', label: '24-Hr Slow Simmered', icon: '🔥', color: '#ea580c', bg: '#ffedd5' },
    ],
    allergens: { contains: [{ name: 'Dairy', severity: 'moderate', icon: '🥛', note: 'In Churned Butter & Cream' }], freeFrom: ['Gluten', 'Eggs', 'Nuts', 'Soy', 'Shellfish'], crossContactNote: 'Zero wheat contamination.' },
    nutrition: { servingSize: '350g', calories: 410, protein: 16, carbs: 42, fats: 18, fiber: 12, sodium: 490, sugar: 3.8, micronutrients: [{ name: 'Iron', value: '5.8 mg', dv: '32%' }, { name: 'Calcium', value: '140 mg', dv: '14%' }] },
    ingredients: [
      { id: 'urad-dal', name: 'Whole Black Urad Lentils', icon: '🥣', category: 'Legume', origin: 'Organic Punjab Cooperative', benefit: 'Super-rich in soluble prebiotic fiber and mineral iron.', calories: 180, protein: 12, allergens: [], certifications: ['Organic Certified'] },
      { id: 'butter', name: 'Fresh White Butter (Makhan)', icon: '🧈', category: 'Dairy', origin: 'Grass-fed cow milk churned daily', benefit: 'Pure clean dairy fat without preservatives.', calories: 120, protein: 0.5, allergens: ['Dairy'], certifications: ['Locally Churned'] },
    ],
    customizationOptions: {
      bases: { title: 'Preparation Style', required: true, maxSelect: 1, options: [{ id: 'traditional', name: 'Traditional Creamy Dhaba Style', price: 0, calories: 50, protein: 1, allergens: ['Dairy'] }, { id: 'low-cream', name: 'Light Cream (Low Calorie)', price: 0, calories: 0, protein: 0, allergens: ['Dairy'] }] },
      proteins: { title: 'Extra Additions', required: false, maxSelect: 1, options: [{ id: 'extra-paneer', name: 'Charred Paneer Cubes (4 pcs)', price: 45, calories: 90, protein: 7, allergens: ['Dairy'] }] },
      toppings: { title: 'Bread Pairings', required: false, maxSelect: 1, options: [{ id: 'garlic-naan', name: '1 Butter Garlic Naan', price: 40, calories: 160, protein: 4, allergens: ['Gluten'] }] },
      dressings: { title: 'Fenugreek Herb', required: true, maxSelect: 1, options: [{ id: 'kasuri-methi', name: 'Aromatic Kasuri Methi Dust', price: 0, calories: 5, protein: 0, allergens: [] }] },
    },
  },
  {
    id: 'paneer-tikka-masala',
    restaurantId: 'spice-route',
    name: 'Paneer Tikka Masala Bowl',
    price: 279,
    rating: 4.6,
    reviewsCount: 260,
    image: '/card2_test.jpg',
    category: 'curries',
    tagline: 'Charcoal Smoked Cottage Paneer in Rich Cashew Tomato Gravy',
    description: 'Fresh farm malai paneer skewers charred in the tandoor with bell peppers, simmered in a luscious silky cashew, onion and sun-dried tomato gravy.',
    prepTime: '20-25 mins',
    dietaryFlags: { isVegan: false, isVegetarian: true, isGlutenFree: true, isDairyFree: false, isKeto: false, isNutFree: false, isOrganic: true },
    dietaryBadges: [
      { id: 'veg', label: '100% Vegetarian', icon: '🌱', color: '#16a34a', bg: '#dcfce7' },
      { id: 'protein', label: '22g Protein', icon: '🧀', color: '#b45309', bg: '#fef3c7' },
    ],
    allergens: { contains: [{ name: 'Dairy', severity: 'moderate', icon: '🥛', note: 'In Paneer' }, { name: 'Cashews', severity: 'moderate', icon: '🌰', note: 'In Gravy Paste' }], freeFrom: ['Gluten', 'Eggs', 'Soy', 'Shellfish'], crossContactNote: 'Clean vegetarian prep.' },
    nutrition: { servingSize: '380g', calories: 480, protein: 22, carbs: 34, fats: 26, fiber: 6, sodium: 520, sugar: 4.8, micronutrients: [{ name: 'Calcium', value: '380 mg', dv: '38%' }] },
    ingredients: [
      { id: 'paneer', name: 'Fresh Malai Cottage Cheese', icon: '🧀', category: 'Dairy Protein', origin: 'Daily Grass-Fed Cow Milk', benefit: 'Rich in casein protein and bone-strengthening calcium.', calories: 210, protein: 18, allergens: ['Dairy'], certifications: ['No Starch Added'] },
    ],
    customizationOptions: {
      bases: { title: 'Gravy Richness', required: true, maxSelect: 1, options: [{ id: 'rich-cashew', name: 'Rich Cashew & Tomato Cream', price: 0, calories: 50, protein: 1, allergens: ['Cashews'] }] },
      proteins: { title: 'Portion', required: false, maxSelect: 1, options: [{ id: 'extra-paneer', name: 'Extra 4 Charcoal Paneer Cubes', price: 55, calories: 120, protein: 9, allergens: ['Dairy'] }] },
      toppings: { title: 'Rice or Roti', required: false, maxSelect: 1, options: [{ id: 'jeera-rice', name: 'Steamed Jeera Basmati Rice', price: 40, calories: 150, protein: 3, allergens: [] }] },
      dressings: { title: 'Spice', required: true, maxSelect: 1, options: [{ id: 'medium', name: 'Mild & Creamy', price: 0, calories: 0, protein: 0, allergens: [] }] },
    },
  },

  /* ---------------- LA PIZZERIA ---------------- */
  {
    id: 'margherita-rustica',
    restaurantId: 'la-pizzeria',
    name: 'Artisan Margherita Rustica',
    price: 299,
    rating: 4.8,
    reviewsCount: 380,
    image: '/cuisine-continental.jpg',
    category: 'pizza',
    tagline: '48-Hr Fermented Sourdough, San Marzano DOP Sauce & Fresh Buffalo Mozzarella',
    description: 'Hand-stretched naturally fermented sourdough base, Italian San Marzano plum tomato sauce, melted buffalo mozzarella, sweet garden basil, and a drizzle of cold-pressed EVOO.',
    prepTime: '20-25 mins',
    dietaryFlags: { isVegan: false, isVegetarian: true, isGlutenFree: false, isDairyFree: false, isKeto: false, isNutFree: true, isOrganic: true },
    dietaryBadges: [
      { id: 'sourdough', label: '48-Hr Sourdough', icon: '🍕', color: '#16a34a', bg: '#dcfce7' },
      { id: 'dop', label: 'San Marzano DOP', icon: '🍅', color: '#ea580c', bg: '#ffedd5' },
    ],
    allergens: { contains: [{ name: 'Gluten', severity: 'moderate', icon: '🌾', note: 'In Sourdough Crust' }, { name: 'Dairy', severity: 'moderate', icon: '🥛', note: 'In Mozzarella' }], freeFrom: ['Nuts', 'Eggs', 'Soy', 'Shellfish'], crossContactNote: 'Baked in stone woodfired deck.' },
    nutrition: { servingSize: '340g (10 inch)', calories: 580, protein: 24, carbs: 72, fats: 19, fiber: 5.5, sodium: 590, sugar: 3.2, micronutrients: [{ name: 'Calcium', value: '310 mg', dv: '31%' }, { name: 'Lycopene', value: '8.4 mg', dv: '100%' }] },
    ingredients: [
      { id: 'flour', name: 'Caputo 00 Italian Flour', icon: '🌾', category: 'Crust', origin: 'Naples, Italy Import', benefit: '48-hr slow cold-rise fermentation produces prebiotic enzymes and easy digestion.', calories: 240, protein: 8, allergens: ['Gluten'], certifications: ['Non-Bleached'] },
      { id: 'mozzarella', name: 'Fresh Buffalo Mozzarella', icon: '🧀', category: 'Cheese', origin: 'Local Artisanal Italian Dairy', benefit: 'High in bioavailable calcium and natural probiotics.', calories: 160, protein: 14, allergens: ['Dairy'], certifications: ['100% Whole Milk'] },
    ],
    customizationOptions: {
      bases: { title: 'Crust Thickness', required: true, maxSelect: 1, options: [{ id: 'neapolitan', name: 'Neapolitan Airy Crust (Standard)', price: 0, calories: 0, protein: 0, allergens: ['Gluten'] }, { id: 'thin-crisp', name: 'Thin & Crispy Roman Style', price: 0, calories: -20, protein: 0, allergens: ['Gluten'] }] },
      proteins: { title: 'Cheese Style', required: false, maxSelect: 1, options: [{ id: 'extra-burrata', name: 'Center Creamy Fresh Burrata (+100g)', price: 75, calories: 140, protein: 8, allergens: ['Dairy'] }] },
      toppings: { title: 'Gourmet Toppings', required: false, maxSelect: 3, options: [{ id: 'olives', name: 'Black Kalamata Olives', price: 25, calories: 35, protein: 0.5, allergens: [] }, { id: 'jalapenos', name: 'Pickled Jalapeno Slices', price: 20, calories: 15, protein: 0.2, allergens: [] }] },
      dressings: { title: 'Finishing Oil', required: true, maxSelect: 1, options: [{ id: 'evoo', name: 'Tuscan Extra Virgin Olive Oil Drizzle', price: 0, calories: 40, protein: 0, allergens: [] }, { id: 'chili-oil', name: 'Infused Calabrian Chili Oil', price: 10, calories: 40, protein: 0, allergens: [] }] },
    },
  },
  {
    id: 'basil-pesto-penne',
    restaurantId: 'la-pizzeria',
    name: 'Zesty Basil Pesto Penne',
    price: 279,
    rating: 4.7,
    reviewsCount: 220,
    image: '/pesto-pasta.jpg',
    category: 'pastas',
    tagline: 'Bronze-Cut Durum Penne, Stone-Ground Pine Nut Pesto & Grana Padano',
    description: 'Al dente Italian durum wheat penne tossed in fragrant stone-ground Genovese basil pesto, toasted pine nuts, cold-pressed olive oil, roasted cherry tomatoes, and aged Grana Padano.',
    prepTime: '15-20 mins',
    dietaryFlags: { isVegan: false, isVegetarian: true, isGlutenFree: false, isDairyFree: false, isKeto: false, isNutFree: false, isOrganic: true },
    dietaryBadges: [
      { id: 'veg', label: '100% Vegetarian', icon: '🌱', color: '#16a34a', bg: '#dcfce7' },
      { id: 'pesto', label: 'Fresh Basil Pesto', icon: '🌿', color: '#059669', bg: '#e8f5ec' },
    ],
    allergens: { contains: [{ name: 'Gluten', severity: 'moderate', icon: '🌾', note: 'In Durum Pasta' }, { name: 'Dairy', severity: 'mild', icon: '🥛', note: 'In Grana Padano' }, { name: 'Pine Nuts', severity: 'mild', icon: '🌰', note: 'In Pesto' }], freeFrom: ['Eggs', 'Soy', 'Shellfish'], crossContactNote: 'Gluten-free penne available.' },
    nutrition: { servingSize: '360g', calories: 510, protein: 17, carbs: 64, fats: 21, fiber: 6.8, sodium: 390, sugar: 3.4, micronutrients: [{ name: 'Vitamin K', value: '45 mcg', dv: '38%' }] },
    ingredients: [
      { id: 'pasta', name: 'Bronze-Cut Durum Wheat Penne', icon: '🍝', category: 'Grain', origin: 'Puglia, Italy', benefit: 'Rough bronze-cut texture holds olive oil emulsion perfectly.', calories: 230, protein: 8, allergens: ['Gluten'], certifications: ['100% Semolina'] },
      { id: 'pesto', name: 'Fresh Genovese Basil Pesto', icon: '🌿', category: 'Sauce', origin: 'Pounded fresh with Mediterranean pine nuts', benefit: 'Loaded with polyphenols and natural plant essential oils.', calories: 150, protein: 4, allergens: ['Pine Nuts', 'Dairy'], certifications: ['Cold Stone Ground'] },
    ],
    customizationOptions: {
      bases: { title: 'Pasta Type', required: true, maxSelect: 1, options: [{ id: 'durum-penne', name: 'Italian Durum Wheat Penne (Standard)', price: 0, calories: 0, protein: 0, allergens: ['Gluten'] }, { id: 'gf-penne', name: 'Gluten-Free Rice & Corn Penne', price: 30, calories: -10, protein: -2, allergens: [] }] },
      proteins: { title: 'Add Protein', required: false, maxSelect: 1, options: [{ id: 'grilled-chicken', name: 'Herb Grilled Chicken Strips', price: 60, calories: 110, protein: 22, allergens: [] }, { id: 'roasted-mushrooms', name: 'Garlic Butter Sautéed Mushrooms', price: 35, calories: 40, protein: 2, allergens: [] }] },
      toppings: { title: 'Extra Cheese', required: false, maxSelect: 1, options: [{ id: 'extra-parm', name: 'Freshly Shaved Grana Padano', price: 30, calories: 50, protein: 4, allergens: ['Dairy'] }] },
      dressings: { title: 'Heat Level', required: true, maxSelect: 1, options: [{ id: 'mild', name: 'Classic Herb Mild', price: 0, calories: 0, protein: 0, allergens: [] }, { id: 'spicy-flake', name: 'Tossed with Red Pepper Chili Flakes', price: 0, calories: 5, protein: 0, allergens: [] }] },
    },
  },

  /* ---------------- BURGER HUB ---------------- */
  {
    id: 'truffle-smash-burger',
    restaurantId: 'burger-hub',
    name: 'Truffle Smash Gourmet Burger',
    price: 289,
    rating: 4.7,
    reviewsCount: 310,
    image: '/cuisine-fastfood.jpg',
    category: 'burgers',
    tagline: 'Fresh Brioche Bun, Smashed Patty, Truffle Aioli, Emmental Cheese & Caramelized Onions',
    description: 'Fluffy butter brioche bun toasted golden, premium smashed patty with crispy caramelized edges, melted Swiss Emmental cheese, slow-cooked balsamic onions, and black truffle aioli.',
    prepTime: '15-20 mins',
    dietaryFlags: { isVegan: false, isVegetarian: false, isGlutenFree: false, isDairyFree: false, isKeto: false, isNutFree: true, isOrganic: false },
    dietaryBadges: [
      { id: 'gourmet', label: 'Gourmet Smashed', icon: '🍔', color: '#ea580c', bg: '#ffedd5' },
      { id: 'protein', label: '26g Protein', icon: '🥩', color: '#b45309', bg: '#fef3c7' },
    ],
    allergens: { contains: [{ name: 'Gluten', severity: 'moderate', icon: '🌾', note: 'In Brioche Bun' }, { name: 'Dairy', severity: 'moderate', icon: '🥛', note: 'In Swiss Cheese & Brioche' }, { name: 'Eggs', severity: 'mild', icon: '🥚', note: 'In Truffle Aioli' }], freeFrom: ['Nuts', 'Soy', 'Shellfish'], crossContactNote: 'Cooked on a dedicated cast iron flattop.' },
    nutrition: { servingSize: '320g', calories: 590, protein: 26, carbs: 48, fats: 28, fiber: 3.5, sodium: 640, sugar: 5.2, micronutrients: [{ name: 'Zinc', value: '4.5 mg', dv: '41%' }] },
    ingredients: [
      { id: 'bun', name: 'Butter Glazed Brioche Bun', icon: '🍞', category: 'Bun', origin: 'Local Artisanal Patisserie', benefit: 'Soft pillowy texture enriched with whole butter and eggs.', calories: 180, protein: 5, allergens: ['Gluten', 'Dairy', 'Eggs'], certifications: ['Baked Daily'] },
      { id: 'patty', name: 'Signature Smashed Patty', icon: '🥩', category: 'Patty', origin: 'Daily Fresh Mince', benefit: 'High-heat smash technique creates delicious Maillard crunch.', calories: 240, protein: 20, allergens: [], certifications: ['100% Whole Cut'] },
    ],
    customizationOptions: {
      bases: { title: 'Bun Choice', required: true, maxSelect: 1, options: [{ id: 'brioche', name: 'Golden Brioche Bun (Standard)', price: 0, calories: 180, protein: 5, allergens: ['Gluten', 'Dairy'] }, { id: 'whole-wheat', name: 'Multigrain Whole Wheat Bun', price: 0, calories: 150, protein: 6, allergens: ['Gluten'] }, { id: 'lettuce-wrap', name: 'Keto Crisp Iceberg Lettuce Wrap', price: 0, calories: 20, protein: 1, allergens: [] }] },
      proteins: { title: 'Double Down', required: false, maxSelect: 1, options: [{ id: 'extra-patty', name: 'Add Extra Smashed Patty (+100g)', price: 75, calories: 190, protein: 18, allergens: [] }, { id: 'extra-cheese', name: 'Extra Melted Swiss Emmental Slice', price: 30, calories: 70, protein: 5, allergens: ['Dairy'] }] },
      toppings: { title: 'Add-Ons', required: false, maxSelect: 2, options: [{ id: 'jalapeno', name: 'Pickled Smoked Jalapenos', price: 20, calories: 10, protein: 0, allergens: [] }, { id: 'mushrooms', name: 'Sauteed Truffle Mushrooms', price: 35, calories: 40, protein: 2, allergens: [] }] },
      dressings: { title: 'Sauce', required: true, maxSelect: 1, options: [{ id: 'truffle-aioli', name: 'Black Truffle Aioli (Standard)', price: 0, calories: 60, protein: 0.5, allergens: ['Eggs'] }, { id: 'chipotle', name: 'Smoky Chipotle Mayo', price: 0, calories: 50, protein: 0.5, allergens: ['Eggs'] }] },
    },
  },
  {
    id: 'rosemary-sea-salt-fries',
    restaurantId: 'burger-hub',
    name: 'Rosemary Sea Salt Hand-Cut Fries',
    price: 139,
    rating: 4.6,
    reviewsCount: 290,
    image: '/checkout-fries.jpg',
    category: 'sides',
    tagline: 'Non-GMO Potatoes, Cold-Pressed Sunflower Oil & Fresh Mountain Rosemary',
    description: 'Skin-on hand-cut potatoes double cooked for a crispy exterior and fluffy center, tossed with crushed Himalayan pink salt and fresh fragrant rosemary needle herbs.',
    prepTime: '10-12 mins',
    dietaryFlags: { isVegan: true, isVegetarian: true, isGlutenFree: true, isDairyFree: true, isKeto: false, isNutFree: true, isOrganic: true },
    dietaryBadges: [
      { id: 'vegan', label: '100% Vegan', icon: '🌱', color: '#16a34a', bg: '#dcfce7' },
      { id: 'fresh', label: 'Hand-Cut Skin-On', icon: '🥔', color: '#ca8a04', bg: '#fef9c3' },
    ],
    allergens: { contains: [], freeFrom: ['Dairy', 'Gluten', 'Eggs', 'Nuts', 'Soy'], crossContactNote: 'Fried in a dedicated potato fryer.' },
    nutrition: { servingSize: '200g', calories: 310, protein: 4.2, carbs: 44, fats: 12, fiber: 5.1, sodium: 320, sugar: 0.8, micronutrients: [{ name: 'Potassium', value: '620 mg', dv: '13%' }] },
    ingredients: [
      { id: 'potatoes', name: 'Non-GMO Russet Potatoes', icon: '🥔', category: 'Produce', origin: 'Direct Farm Contract', benefit: 'Skin-on preparation retains rich potassium and dietary fiber.', calories: 210, protein: 3.5, allergens: [], certifications: ['Non-GMO'] },
    ],
    customizationOptions: {
      bases: { title: 'Seasoning', required: true, maxSelect: 1, options: [{ id: 'rosemary-salt', name: 'Fresh Rosemary & Pink Sea Salt', price: 0, calories: 0, protein: 0, allergens: [] }, { id: 'cajun-spice', name: 'Spicy Cajun Paprika Dust', price: 10, calories: 5, protein: 0, allergens: [] }] },
      proteins: { title: 'Loaded Toppings', required: false, maxSelect: 1, options: [{ id: 'cheese-sauce', name: 'Warm Cheddar Melt Dip', price: 35, calories: 80, protein: 3, allergens: ['Dairy'] }] },
      toppings: { title: 'Dipping Sauce', required: false, maxSelect: 2, options: [{ id: 'garlic-mayo', name: 'Herb Garlic Dip', price: 20, calories: 50, protein: 0, allergens: ['Eggs'] }] },
      dressings: { title: 'Salt Level', required: true, maxSelect: 1, options: [{ id: 'regular-salt', name: 'Regular Seasoning', price: 0, calories: 0, protein: 0, allergens: [] }, { id: 'low-salt', name: 'Light Salt (Low Sodium)', price: 0, calories: 0, protein: 0, allergens: [] }] },
    },
  },

  /* ---------------- URBAN ASIA ---------------- */
  {
    id: 'edamame-truffle-dimsums',
    restaurantId: 'urban-asia',
    name: 'Steamed Edamame Truffle Dimsums',
    price: 289,
    rating: 4.8,
    reviewsCount: 275,
    image: '/info-noodle-bowl.jpg',
    category: 'dimsums',
    tagline: 'Translucent Wheat Skin, Steamed Edamame & Water Chestnuts with Truffle Oil',
    description: 'Delicate handmade crystal dumplings stuffed with crushed young edamame beans, crunchy water chestnuts, shiitake mushrooms, and aromatic white truffle oil, served with scallion chili dip.',
    prepTime: '15-20 mins',
    dietaryFlags: { isVegan: true, isVegetarian: true, isGlutenFree: false, isDairyFree: true, isKeto: false, isNutFree: true, isOrganic: true },
    dietaryBadges: [
      { id: 'vegan', label: '100% Vegan', icon: '🌱', color: '#16a34a', bg: '#dcfce7' },
      { id: 'steamed', label: 'Zero Oil Steamed', icon: '🥟', color: '#059669', bg: '#e8f5ec' },
    ],
    allergens: { contains: [{ name: 'Soy', severity: 'moderate', icon: '🌱', note: 'In Edamame' }, { name: 'Gluten', severity: 'mild', icon: '🌾', note: 'In Dumpling Skin' }], freeFrom: ['Dairy', 'Eggs', 'Nuts', 'Peanuts', 'Shellfish'], crossContactNote: 'Steamed in bamboo baskets.' },
    nutrition: { servingSize: '6 pieces (240g)', calories: 280, protein: 14, carbs: 38, fats: 6, fiber: 5.5, sodium: 380, sugar: 2.1, micronutrients: [{ name: 'Folate', value: '110 mcg', dv: '28%' }] },
    ingredients: [
      { id: 'edamame', name: 'Young Green Edamame', icon: '🫘', category: 'Plant Protein', origin: 'Non-GMO Pod Harvest', benefit: 'Packed with plant isoflavones, iron, and complete proteins.', calories: 120, protein: 11, allergens: ['Soy'], certifications: ['Non-GMO'] },
    ],
    customizationOptions: {
      bases: { title: 'Portion', required: true, maxSelect: 1, options: [{ id: '6-pcs', name: '6 Steamed Pieces (Standard)', price: 0, calories: 0, protein: 0, allergens: [] }, { id: '9-pcs', name: '9 Steamed Pieces', price: 90, calories: 140, protein: 7, allergens: [] }] },
      proteins: { title: 'Dip Selection', required: false, maxSelect: 2, options: [{ id: 'chili-crisp', name: 'House Scallion Chili Crisp Oil', price: 15, calories: 35, protein: 0, allergens: ['Sesame'] }, { id: 'tamari', name: 'Gluten-Free Ginger Tamari Dip', price: 10, calories: 15, protein: 1, allergens: ['Soy'] }] },
      toppings: { title: 'Crispy Garlic', required: false, maxSelect: 1, options: [{ id: 'garlic-crunch', name: 'Toasted Golden Garlic Crunch', price: 15, calories: 20, protein: 0.5, allergens: [] }] },
      dressings: { title: 'Steaming Herb', required: true, maxSelect: 1, options: [{ id: 'truffle', name: 'White Truffle Essence Infusion', price: 0, calories: 0, protein: 0, allergens: [] }] },
    },
  },
  {
    id: 'pad-thai-wok-noodles',
    restaurantId: 'urban-asia',
    name: 'Pad Thai Wok Tossed Noodles',
    price: 299,
    rating: 4.7,
    reviewsCount: 240,
    image: '/cuisine-chinese.jpg',
    category: 'noodles',
    tagline: 'Flat Rice Noodles, Tamarind Palm Glaze, Tofu, Bean Sprouts & Crushed Peanuts',
    description: 'Authentic Bangkok street style flat rice noodles tossed over high flame with tangy tamarind pulp, palm jaggery, firm tofu, chives, crunchy bean sprouts, and toasted crushed peanuts.',
    prepTime: '15-20 mins',
    dietaryFlags: { isVegan: true, isVegetarian: true, isGlutenFree: true, isDairyFree: true, isKeto: false, isNutFree: false, isOrganic: false },
    dietaryBadges: [
      { id: 'glutenFree', label: 'Gluten-Free Rice Noodles', icon: '🌾', color: '#0d9488', bg: '#ccfbf1' },
      { id: 'vegan', label: 'Plant-Based', icon: '🌱', color: '#16a34a', bg: '#dcfce7' },
    ],
    allergens: { contains: [{ name: 'Peanuts', severity: 'moderate', icon: '🥜', note: 'Topping (can be omitted)' }, { name: 'Soy', severity: 'mild', icon: '🌱', note: 'In Tofu & Sauce' }], freeFrom: ['Gluten', 'Dairy', 'Eggs', 'Shellfish'], crossContactNote: 'Wok sanitised before gluten-free batches.' },
    nutrition: { servingSize: '380g', calories: 490, protein: 16, carbs: 68, fats: 16, fiber: 6, sodium: 490, sugar: 7.5, micronutrients: [{ name: 'Vitamin C', value: '24 mg', dv: '27%' }] },
    ingredients: [
      { id: 'rice-noodles', name: 'Artisan Rice Flat Noodles', icon: '🍜', category: 'Grain Base', origin: 'Traditional Rice Milling', benefit: 'Naturally gluten-free, light and fast digesting.', calories: 220, protein: 4, allergens: [], certifications: ['100% Rice Flour'] },
    ],
    customizationOptions: {
      bases: { title: 'Noodle Type', required: true, maxSelect: 1, options: [{ id: 'rice-noodle', name: 'Flat Rice Noodles (Standard)', price: 0, calories: 0, protein: 0, allergens: [] }] },
      proteins: { title: 'Protein Addition', required: false, maxSelect: 1, options: [{ id: 'chicken-katsu', name: 'Crispy Herb Chicken Breast', price: 65, calories: 130, protein: 24, allergens: [] }, { id: 'extra-tofu', name: 'Firm Organic Tofu Cubes', price: 35, calories: 75, protein: 9, allergens: ['Soy'] }] },
      toppings: { title: 'Peanut Crunch', required: false, maxSelect: 1, options: [{ id: 'peanuts', name: 'Roasted Crushed Peanuts on Side', price: 0, calories: 50, protein: 2, allergens: ['Peanuts'] }, { id: 'no-peanuts', name: 'Nut-Free (No Peanuts)', price: 0, calories: 0, protein: 0, allergens: [] }] },
      dressings: { title: 'Spice Level', required: true, maxSelect: 1, options: [{ id: 'thai-medium', name: 'Balanced Sweet & Tangy Medium', price: 0, calories: 0, protein: 0, allergens: [] }, { id: 'thai-spicy', name: 'Bird’s Eye Chili Spicy', price: 0, calories: 5, protein: 0, allergens: [] }] },
    },
  },

  /* ---------------- SWEET CRAVINGS ---------------- */
  {
    id: 'belgian-dark-ganache-cake',
    restaurantId: 'sweet-cravings',
    name: 'Belgian Dark Ganache Slice',
    price: 189,
    rating: 4.9,
    reviewsCount: 350,
    image: '/cuisine-desserts.jpg',
    category: 'cakes',
    tagline: '70% Single-Origin Belgian Cocoa, Cold-Pressed Coconut Oil & Zero Refined Sugar',
    description: 'Decadent moist chocolate sponge layered with velvety 70% dark Belgian ganache, sweetened exclusively with organic date syrup and raw jaggery.',
    prepTime: '5-10 mins',
    dietaryFlags: { isVegan: true, isVegetarian: true, isGlutenFree: false, isDairyFree: true, isKeto: false, isNutFree: true, isOrganic: true },
    dietaryBadges: [
      { id: 'sugarFree', label: 'Zero Refined Sugar', icon: '✨', color: '#7c3aed', bg: '#f3e8ff' },
      { id: 'darkChoc', label: '70% Belgian Dark Cocoa', icon: '🍫', color: '#b45309', bg: '#fef3c7' },
    ],
    allergens: { contains: [{ name: 'Gluten', severity: 'mild', icon: '🌾', note: 'In Wheat Flour' }], freeFrom: ['Dairy', 'Eggs', 'Nuts', 'Peanuts', 'Soy'], crossContactNote: 'Nut-free bakery line.' },
    nutrition: { servingSize: '140g slice', calories: 320, protein: 6.5, carbs: 38, fats: 14, fiber: 5.2, sodium: 110, sugar: 14, micronutrients: [{ name: 'Iron', value: '4.1 mg', dv: '23%' }, { name: 'Magnesium', value: '88 mg', dv: '21%' }] },
    ingredients: [
      { id: 'cocoa', name: '70% Single-Origin Cocoa', icon: '🍫', category: 'Superfood', origin: 'Fair-Trade Certified Belgian Imports', benefit: 'Extremely high in flavanol antioxidants for cellular protection and heart health.', calories: 130, protein: 4, allergens: [], certifications: ['Fair-Trade'] },
      { id: 'dates', name: 'Organic Medjool Date Syrup', icon: '🌴', category: 'Natural Sweetener', origin: 'Sun-dried natural date reduction', benefit: 'Low-glycemic natural sweetener rich in potassium and fiber.', calories: 90, protein: 0.8, allergens: [], certifications: ['100% Unrefined'] },
    ],
    customizationOptions: {
      bases: { title: 'Serving Temperature', required: true, maxSelect: 1, options: [{ id: 'warm', name: 'Warm & Gooey (Warmed in Oven)', price: 0, calories: 0, protein: 0, allergens: [] }, { id: 'chilled', name: 'Chilled Fudgy Slice', price: 0, calories: 0, protein: 0, allergens: [] }] },
      proteins: { title: 'Add-Ons', required: false, maxSelect: 1, options: [{ id: 'berry-compote', name: 'Wild Raspberry Compote (Zero Sugar)', price: 25, calories: 30, protein: 0.5, allergens: [] }] },
      toppings: { title: 'Crunch', required: false, maxSelect: 1, options: [{ id: 'cacao-nibs', name: 'Raw Crunchy Cacao Nibs', price: 20, calories: 25, protein: 0.8, allergens: [] }] },
      dressings: { title: 'Drizzle', required: true, maxSelect: 1, options: [{ id: 'dark-drizzle', name: 'Warm Dark Cocoa Glaze', price: 0, calories: 25, protein: 0.2, allergens: [] }] },
    },
  },
  {
    id: 'walnut-fudge-brownie',
    restaurantId: 'sweet-cravings',
    name: 'Gluten-Free Walnut Fudge Brownie',
    price: 159,
    rating: 4.8,
    reviewsCount: 290,
    image: '/checkout-brownie.jpg',
    category: 'brownies',
    tagline: 'Almond & Ragi Flour, Toasted Walnuts, Raw Cacao & Coconut Nectar',
    description: 'Ultra-dense fudgy brownie crafted with sprouted ragi and almond flour, loaded with buttery Kashmiri walnuts and sweetened with unrefined coconut palm nectar.',
    prepTime: '5-10 mins',
    dietaryFlags: { isVegan: true, isVegetarian: true, isGlutenFree: true, isDairyFree: true, isKeto: false, isNutFree: false, isOrganic: true },
    dietaryBadges: [
      { id: 'glutenFree', label: '100% Gluten-Free', icon: '🌾', color: '#0d9488', bg: '#ccfbf1' },
      { id: 'omega3', label: 'Walnut Omega-3', icon: '🌰', color: '#059669', bg: '#e8f5ec' },
    ],
    allergens: { contains: [{ name: 'Walnuts', severity: 'moderate', icon: '🌰', note: 'In Brownie Mix' }, { name: 'Almonds', severity: 'mild', icon: '🌰', note: 'In Flour Base' }], freeFrom: ['Gluten', 'Dairy', 'Eggs', 'Soy'], crossContactNote: 'Gluten-free certified kitchen.' },
    nutrition: { servingSize: '110g', calories: 290, protein: 7.2, carbs: 28, fats: 16, fiber: 6.4, sodium: 85, sugar: 11, micronutrients: [{ name: 'Omega-3 ALA', value: '1800 mg', dv: '112%' }] },
    ingredients: [
      { id: 'walnuts', name: 'Kashmiri Sun-Dried Walnuts', icon: '🌰', category: 'Nut Base', origin: 'Kashmir Valley Organic Groves', benefit: 'The richest plant source of neuroprotective Omega-3 ALA fatty acids.', calories: 120, protein: 3.5, allergens: ['Tree Nuts'], certifications: ['Wild Harvested'] },
    ],
    customizationOptions: {
      bases: { title: 'Preparation', required: true, maxSelect: 1, options: [{ id: 'warmed', name: 'Warmed with Molten Fudge Core', price: 0, calories: 0, protein: 0, allergens: [] }] },
      proteins: { title: 'Ice Cream Side', required: false, maxSelect: 1, options: [{ id: 'vegan-vanilla', name: '1 Scoop Coconut Milk Vanilla Ice Cream', price: 45, calories: 80, protein: 1, allergens: [] }] },
      toppings: { title: 'Toppings', required: false, maxSelect: 1, options: [{ id: 'sea-salt', name: 'Flaky Maldon Smoked Sea Salt', price: 0, calories: 0, protein: 0, allergens: [] }] },
      dressings: { title: 'Sauce', required: true, maxSelect: 1, options: [{ id: 'fudge-sauce', name: 'Warm Coconut Fudge Drizzle', price: 0, calories: 30, protein: 0.5, allergens: [] }] },
    },
  },
];

/* =========================================================
   Helper Lookup Functions
   ========================================================= */

export function getRestaurantById(idOrSlug) {
  if (!idOrSlug) return restaurants[0];
  const query = String(idOrSlug).toLowerCase();
  return (
    restaurants.find(
      (r) => r.id === query || String(r.numericId) === query || r.name.toLowerCase().includes(query)
    ) || restaurants[0]
  );
}

export function getFoodItemById(id) {
  if (!id) return foodItems[0];
  const query = String(id).toLowerCase();
  return (
    foodItems.find((item) => item.id === query || item.name.toLowerCase().includes(query)) ||
    foodItems[0]
  );
}

export function getFoodItemsByRestaurant(restaurantId) {
  const restaurant = getRestaurantById(restaurantId);
  if (!restaurant) return foodItems.slice(0, 4);
  const items = foodItems.filter((item) => item.restaurantId === restaurant.id);
  return items.length > 0 ? items : foodItems.slice(0, 4);
}
