/**
 * ClearBite Central Live Food & Nutrition Dataset
 * Complete with ingredient origins, allergen matrix, micronutrients & customizable options.
 */

export const foodItems = [
  {
    id: 'quinoa-power-bowl',
    name: 'Quinoa Power Bowl',
    price: 249,
    rating: 4.8,
    reviewsCount: 340,
    image: '/quinoa-power-bowl.jpg',
    category: 'bowls',
    tagline: '100% Organic Tri-Color Quinoa with Fire-Roasted Seasonal Veggies & Lemon Tahini',
    description:
      'A deeply satisfying and wholesome bowl crafted with organic Andean tri-color quinoa, hand-sliced Hass avocado, steamed hydroponic broccoli, roasted Nilgiri carrots, vine cherry tomatoes, superfood chia & pumpkin seeds, and a zesty house lemon tahini vinaigrette.',
    prepTime: '15-20 mins',
    dietaryFlags: {
      isVegan: true,
      isVegetarian: true,
      isGlutenFree: true,
      isDairyFree: true,
      isKeto: false,
      isNutFree: false,
      isOrganic: true,
    },
    dietaryBadges: [
      { id: 'vegan', label: '100% Vegan', icon: '🌱', color: '#16a34a', bg: '#dcfce7' },
      { id: 'glutenFree', label: 'Gluten-Free', icon: '🌾', color: '#0d9488', bg: '#ccfbf1' },
      { id: 'dairyFree', label: 'Dairy-Free', icon: '🥛', color: '#2563eb', bg: '#dbeafe' },
      { id: 'highFiber', label: 'High Fiber (9.5g)', icon: '🥗', color: '#059669', bg: '#e8f5ec' },
      { id: 'cleanLabel', label: 'Zero Artificial Additives', icon: '✨', color: '#7c3aed', bg: '#f3e8ff' },
    ],
    allergens: {
      contains: [
        { name: 'Sesame', severity: 'moderate', icon: '🌱', note: 'Present in Creamy Lemon Tahini' },
        { name: 'Pumpkin & Chia Seeds', severity: 'mild', icon: '🌰', note: 'Seed crunch mix (can be omitted)' },
      ],
      freeFrom: ['Gluten', 'Dairy', 'Eggs', 'Peanuts', 'Soy', 'Shellfish', 'Preservatives'],
      crossContactNote: 'Prepared in an ISO-certified clean kitchen with isolated allergen prep stations.',
    },
    nutrition: {
      servingSize: '380g',
      calories: 450,
      protein: 18,
      carbs: 52,
      fats: 14,
      fiber: 9.5,
      sodium: 320,
      sugar: 4.2,
      micronutrients: [
        { name: 'Potassium', value: '720 mg', dv: '15%' },
        { name: 'Iron', value: '4.8 mg', dv: '27%' },
        { name: 'Magnesium', value: '118 mg', dv: '28%' },
        { name: 'Folate', value: '142 mcg', dv: '36%' },
        { name: 'Vitamin C', value: '38 mg', dv: '42%' },
        { name: 'Calcium', value: '88 mg', dv: '9%' },
      ],
    },
    ingredients: [
      {
        id: 'quinoa',
        name: 'Tri-Color Quinoa',
        icon: '🥣',
        category: 'Ancient Grain Base',
        origin: 'Certified Organic High-Altitude Farms',
        benefit: 'Complete plant protein loaded with all 9 essential amino acids & slow-release low GI carbs.',
        calories: 140,
        protein: 5.2,
        allergens: [],
        certifications: ['USDA Organic', 'Non-GMO'],
      },
      {
        id: 'avocado',
        name: 'Hass Avocado',
        icon: '🥑',
        category: 'Healthy Fats',
        origin: 'Tree-ripened, hand-sliced daily',
        benefit: 'Rich in monounsaturated oleic acid, heart-healthy sterols and potassium.',
        calories: 90,
        protein: 1.2,
        allergens: [],
        certifications: ['Fresh Farm Picked'],
      },
      {
        id: 'broccoli',
        name: 'Steamed Broccoli',
        icon: '🥦',
        category: 'Cruciferous Greens',
        origin: 'Local Hydroponic Greenhouse',
        benefit: 'Packed with sulforaphane, immune-boosting Vitamin C, and bioavailable folate.',
        calories: 30,
        protein: 2.8,
        allergens: [],
        certifications: ['Pesticide Free'],
      },
      {
        id: 'carrot',
        name: 'Fire-Roasted Carrots',
        icon: '🥕',
        category: 'Root Vegetables',
        origin: 'Nilgiri Hillside Harvest',
        benefit: 'Abundant in beta-carotene for cellular antioxidant defense and skin vitality.',
        calories: 25,
        protein: 0.6,
        allergens: [],
        certifications: ['Locally Sourced'],
      },
      {
        id: 'tomatoes',
        name: 'Vine Cherry Tomatoes',
        icon: '🍅',
        category: 'Sun Produce',
        origin: 'Hydroponic Sweet Vine Harvest',
        benefit: 'Rich in lycopene, promoting cardiovascular endurance and reducing inflammation.',
        calories: 20,
        protein: 0.9,
        allergens: [],
        certifications: ['Non-GMO'],
      },
      {
        id: 'seeds',
        name: 'Chia & Pumpkin Seeds',
        icon: '🌰',
        category: 'Superfood Crunch',
        origin: 'Raw Unprocessed Sun-Dried',
        benefit: 'High-density plant Omega-3 fatty acids, zinc, and magnesium.',
        calories: 55,
        protein: 3.4,
        allergens: ['Seeds'],
        certifications: ['Raw Superfood'],
      },
      {
        id: 'greens',
        name: 'Baby Arugula & Spinach',
        icon: '🥬',
        category: 'Leafy Supergreens',
        origin: 'Controlled-Environment Vertical Farm',
        benefit: 'Natural nitrates, chlorophyll and vitamin K for blood pressure and oxygenation.',
        calories: 15,
        protein: 1.6,
        allergens: [],
        certifications: ['Zero Pesticides'],
      },
    ],
    customizationOptions: {
      bases: {
        title: 'Choose Your Base Grain / Greens',
        required: true,
        maxSelect: 1,
        options: [
          { id: 'tri-quinoa', name: 'Tri-Color Organic Quinoa (Standard)', price: 0, calories: 140, protein: 5.2, allergens: [] },
          { id: 'brown-rice', name: 'Steamed Brown Basmati Rice', price: 0, calories: 150, protein: 3.8, allergens: [] },
          { id: 'cauli-rice', name: 'Low-Carb Cauliflower Rice', price: 25, calories: 45, protein: 2.1, allergens: [] },
          { id: 'kale-greens', name: 'Supergreens Base (Baby Kale & Arugula)', price: 15, calories: 30, protein: 2.8, allergens: [] },
        ],
      },
      proteins: {
        title: 'Add Extra Plant or Lean Protein',
        required: false,
        maxSelect: 2,
        options: [
          { id: 'grilled-tofu', name: 'Smoked Garlic Herb Tofu (100g)', price: 40, calories: 95, protein: 12, allergens: ['Soy'] },
          { id: 'edamame', name: 'Steamed Salted Edamame', price: 35, calories: 75, protein: 8.5, allergens: ['Soy'] },
          { id: 'grilled-chicken', name: 'Herb Flame Grilled Chicken Breast', price: 65, calories: 130, protein: 26, allergens: [] },
          { id: 'paneer-tikka', name: 'Charcoal Grilled Cottage Paneer', price: 50, calories: 120, protein: 14, allergens: ['Dairy'] },
          { id: 'boiled-eggs', name: '2 Free-Range Boiled Eggs', price: 35, calories: 140, protein: 12, allergens: ['Eggs'] },
        ],
      },
      toppings: {
        title: 'Veggies & Superfood Add-Ons',
        required: false,
        maxSelect: 4,
        options: [
          { id: 'extra-avocado', name: 'Extra Half Hass Avocado', price: 45, calories: 85, protein: 1.2, allergens: [] },
          { id: 'roasted-mushrooms', name: 'Garlic Shiitake Mushrooms', price: 30, calories: 35, protein: 2.2, allergens: [] },
          { id: 'kalamata-olives', name: 'Kalamata Greek Olives', price: 25, calories: 40, protein: 0.5, allergens: [] },
          { id: 'feta-cheese', name: 'Crumbled Feta Cheese', price: 35, calories: 75, protein: 4.1, allergens: ['Dairy'] },
          { id: 'toasted-almonds', name: 'Golden Roasted Almond Slivers', price: 30, calories: 60, protein: 2.6, allergens: ['Tree Nuts'] },
          { id: 'roasted-chickpeas', name: 'Crispy Paprika Chickpeas', price: 20, calories: 50, protein: 2.8, allergens: [] },
        ],
      },
      dressings: {
        title: 'Artisan Dressing',
        required: true,
        maxSelect: 1,
        options: [
          { id: 'lemon-tahini', name: 'Creamy Lemon Tahini (Standard)', price: 0, calories: 65, protein: 1.8, allergens: ['Sesame'] },
          { id: 'balsamic', name: 'Aged Balsamic Dijon Glaze', price: 0, calories: 45, protein: 0.5, allergens: [] },
          { id: 'green-goddess', name: 'Avocado Green Goddess', price: 15, calories: 55, protein: 1.0, allergens: [] },
          { id: 'spicy-chipotle', name: 'Smoky Chipotle Vinaigrette', price: 0, calories: 50, protein: 0.4, allergens: [] },
          { id: 'on-side', name: 'Dressing on the Side (Zero Added Sauce)', price: 0, calories: 0, protein: 0, allergens: [] },
        ],
      },
    },
  },
  {
    id: 'grilled-chicken-salad',
    name: 'Grilled Chicken Salad',
    price: 269,
    rating: 4.9,
    reviewsCount: 280,
    image: '/grilled-chicken-salad.jpg',
    category: 'salads',
    tagline: 'Tender Herb Chicken, Mixed Greens, Cherry Tomatoes & Cold-Pressed Olive Oil',
    description:
      'Skinless antibiotic-free chicken breast seared with rosemary and thyme, served over crisp mixed greens, cucumber ribbons, bell peppers and drizzled with cold-pressed extra virgin olive oil.',
    prepTime: '15-20 mins',
    dietaryFlags: {
      isVegan: false,
      isVegetarian: false,
      isGlutenFree: true,
      isDairyFree: true,
      isKeto: true,
      isNutFree: true,
      isOrganic: true,
    },
    dietaryBadges: [
      { id: 'highProtein', label: 'High Protein (34g)', icon: '🍗', color: '#b45309', bg: '#fef3c7' },
      { id: 'keto', label: 'Keto Friendly', icon: '🥑', color: '#0d9488', bg: '#ccfbf1' },
      { id: 'glutenFree', label: 'Gluten-Free', icon: '🌾', color: '#059669', bg: '#dcfce7' },
      { id: 'dairyFree', label: 'Dairy-Free', icon: '🥛', color: '#2563eb', bg: '#dbeafe' },
    ],
    allergens: {
      contains: [],
      freeFrom: ['Gluten', 'Dairy', 'Nuts', 'Sesame', 'Soy', 'Shellfish'],
      crossContactNote: 'Cooked on a dedicated poultry grill with clean utensils.',
    },
    nutrition: {
      servingSize: '350g',
      calories: 390,
      protein: 34,
      carbs: 16,
      fats: 18,
      fiber: 6.2,
      sodium: 410,
      sugar: 3.1,
      micronutrients: [
        { name: 'Niacin (B3)', value: '14 mg', dv: '88%' },
        { name: 'Vitamin B6', value: '1.2 mg', dv: '70%' },
        { name: 'Selenium', value: '32 mcg', dv: '58%' },
        { name: 'Phosphorus', value: '290 mg', dv: '23%' },
      ],
    },
    ingredients: [
      {
        id: 'chicken-breast',
        name: 'Herb Grilled Chicken',
        icon: '🍗',
        category: 'Lean Protein',
        origin: 'Antibiotic-Free Farm Poultry',
        benefit: 'Lean, complete amino acid profile vital for muscle repair.',
        calories: 180,
        protein: 28,
        allergens: [],
        certifications: ['Antibiotic-Free'],
      },
      {
        id: 'greens',
        name: 'Crisp Mixed Greens',
        icon: '🥬',
        category: 'Leafy Greens',
        origin: 'Vertical Farm Greens',
        benefit: 'High hydration, potassium, and vitamins A & K.',
        calories: 25,
        protein: 2,
        allergens: [],
        certifications: ['Pesticide Free'],
      },
    ],
    customizationOptions: {
      bases: {
        title: 'Salad Base',
        required: true,
        maxSelect: 1,
        options: [
          { id: 'mixed-greens', name: 'Crunchy Romaine & Baby Spinach (Standard)', price: 0, calories: 25, protein: 2, allergens: [] },
          { id: 'arugula', name: 'Peppery Wild Arugula', price: 15, calories: 20, protein: 2.2, allergens: [] },
        ],
      },
      proteins: {
        title: 'Protein Options',
        required: false,
        maxSelect: 1,
        options: [
          { id: 'extra-chicken', name: 'Extra Double Chicken Breast (+100g)', price: 70, calories: 150, protein: 28, allergens: [] },
          { id: 'boiled-eggs', name: '2 Free-Range Boiled Eggs', price: 35, calories: 140, protein: 12, allergens: ['Eggs'] },
        ],
      },
      toppings: {
        title: 'Add-Ons',
        required: false,
        maxSelect: 3,
        options: [
          { id: 'avocado', name: 'Half Hass Avocado', price: 45, calories: 85, protein: 1.2, allergens: [] },
          { id: 'parmesan', name: 'Shaved Aged Parmesan', price: 35, calories: 60, protein: 4.5, allergens: ['Dairy'] },
        ],
      },
      dressings: {
        title: 'Dressing',
        required: true,
        maxSelect: 1,
        options: [
          { id: 'olive-lemon', name: 'Cold-Pressed EVOO & Lemon (Standard)', price: 0, calories: 70, protein: 0, allergens: [] },
          { id: 'caesar', name: 'Light Greek Yogurt Caesar', price: 15, calories: 60, protein: 2, allergens: ['Dairy'] },
        ],
      },
    },
  },
  {
    id: 'mediterranean-bowl',
    name: 'Mediterranean Mezze Bowl',
    price: 279,
    rating: 4.7,
    reviewsCount: 215,
    image: '/mediterranean-bowl.jpg',
    category: 'bowls',
    tagline: 'Roasted Falafel, Creamy Hummus, Tabbouleh & Greek Olives',
    description:
      'Golden herb-baked chickpea falafels with stone-ground sesame hummus, heirloom tabbouleh, pickled red cabbage, cucumber salad, and warm pita wedges.',
    prepTime: '15-20 mins',
    dietaryFlags: {
      isVegan: true,
      isVegetarian: true,
      isGlutenFree: false,
      isDairyFree: true,
      isKeto: false,
      isNutFree: true,
      isOrganic: true,
    },
    dietaryBadges: [
      { id: 'vegan', label: '100% Vegan', icon: '🌱', color: '#16a34a', bg: '#dcfce7' },
      { id: 'highFiber', label: 'High Fiber (11g)', icon: '🥗', color: '#059669', bg: '#e8f5ec' },
      { id: 'dairyFree', label: 'Dairy-Free', icon: '🥛', color: '#2563eb', bg: '#dbeafe' },
    ],
    allergens: {
      contains: [
        { name: 'Sesame', severity: 'moderate', icon: '🌱', note: 'In Hummus & Tahini' },
        { name: 'Gluten', severity: 'moderate', icon: '🌾', note: 'In Pita & Tabbouleh bulgur' },
      ],
      freeFrom: ['Dairy', 'Eggs', 'Nuts', 'Peanuts', 'Shellfish'],
      crossContactNote: 'Gluten-free pita substitute available on request.',
    },
    nutrition: {
      servingSize: '410g',
      calories: 510,
      protein: 19,
      carbs: 68,
      fats: 17,
      fiber: 11.4,
      sodium: 480,
      sugar: 5.5,
      micronutrients: [
        { name: 'Iron', value: '5.2 mg', dv: '29%' },
        { name: 'Folate', value: '180 mcg', dv: '45%' },
        { name: 'Magnesium', value: '95 mg', dv: '23%' },
      ],
    },
    ingredients: [
      {
        id: 'falafel',
        name: 'Baked Herb Falafel',
        icon: '🧆',
        category: 'Plant Protein',
        origin: 'Handmade fresh daily',
        benefit: 'Spiced chickpeas baked with fresh parsley, coriander & cumin.',
        calories: 160,
        protein: 7,
        allergens: [],
        certifications: ['Non-Fried'],
      },
      {
        id: 'hummus',
        name: 'Stone-Ground Hummus',
        icon: '🫒',
        category: 'Dip & Dressing',
        origin: 'Traditional recipe with Greek olive oil',
        benefit: 'Rich in dietary fiber, unsaturated fats, and sesame lignans.',
        calories: 110,
        protein: 4.5,
        allergens: ['Sesame'],
        certifications: ['Artisan Crafted'],
      },
    ],
    customizationOptions: {
      bases: {
        title: 'Grains & Greens',
        required: true,
        maxSelect: 1,
        options: [
          { id: 'tabbouleh', name: 'Parsley Bulgur Tabbouleh (Standard)', price: 0, calories: 120, protein: 3, allergens: ['Gluten'] },
          { id: 'quinoa-sub', name: 'Gluten-Free Tri-Color Quinoa Base', price: 20, calories: 130, protein: 5, allergens: [] },
        ],
      },
      proteins: {
        title: 'Extra Mezze',
        required: false,
        maxSelect: 2,
        options: [
          { id: 'extra-falafel', name: '3 Extra Baked Falafel Pieces', price: 45, calories: 120, protein: 6, allergens: [] },
          { id: 'grilled-halloumi', name: 'Seared Halloumi Cheese Slices', price: 55, calories: 140, protein: 9, allergens: ['Dairy'] },
        ],
      },
      toppings: {
        title: 'Pickles & Toppings',
        required: false,
        maxSelect: 3,
        options: [
          { id: 'olives', name: 'Kalamata Olives', price: 25, calories: 40, protein: 0.5, allergens: [] },
          { id: 'pickled-cabbage', name: 'Tangy Sumac Red Cabbage', price: 15, calories: 20, protein: 0.8, allergens: [] },
        ],
      },
      dressings: {
        title: 'Sauce',
        required: true,
        maxSelect: 1,
        options: [
          { id: 'tahini', name: 'Garlic Tahini Sauce (Standard)', price: 0, calories: 60, protein: 1.5, allergens: ['Sesame'] },
          { id: 'zhug', name: 'Spicy Green Zhug Cilantro Sauce', price: 0, calories: 35, protein: 0.5, allergens: [] },
        ],
      },
    },
  },
];

export function getFoodItemById(id) {
  return foodItems.find((item) => item.id === id) || foodItems[0];
}
